image: python:3.12

stages:
  - lint

py_compile:
  stage: lint
  script:
    - find . -name "*.py" -not -path "./venv/*" -exec python -m py_compile {} +

black:
  stage: lint
  before_script:
    - pip install black
  script:
    - black --check .

isort:
  stage: lint
  before_script:
    - pip install isort
  script:
    - isort --check-only .

antl4r:
  stage: lint
  image: danistomi/antlr4
  script:
    - antlr4 -o antlr_check -no-listener -no-visitor language/Language.g4
    - rm -r antlr_check/

pymarkdownlnt:
  stage: lint
  before_script:
    - pip install pymarkdownlnt
  script:
    - pymarkdown --disable-rules md013 scan docs/

pages:
  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements-mkdocs-build.txt
    - mkdocs --version
    - pwd
  script:
    - mkdocs build
  only:
    - main
  artifacts:
    paths:
    - site
  publish: site
  cache:
    paths:
      - .cache/pip
      - venv

