image: python:3.12

check_py_syntax:
  stage: lint
  script:
    - find . -name "*.py" -not -path "./venv/*" -exec python -m py_compile {} +

black:
  stage: lint
  before_script:
    - pip install black
  script:
    - black --check .

isort:
  stage: lint
  before_script:
    - pip install isort
  script:
    - isort --check-only .

pymarkdownlnt:
  stage: lint
  before_script:
    - pip install pymarkdownlnt
  script:
    - pymarkdown scan docs/

pages:
  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements-mkdocs-build.txt
    - mkdocs --version
    - pwd
  script:
    - mkdocs build
  artifacts:
    paths:
    - site
  publish: site
  cache:
    paths:
      - .cache/pip
      - venv


