image: python:3.12

py_compile:
  stage: test
  script:
    - find . -name "*.py" -not -path "./venv/*" -exec python -m py_compile {} +

black:
  stage: test
  before_script:
    - pip install black
  script:
    - black --check .

isort:
  stage: test
  before_script:
    - pip install isort
  script:
    - isort --check-only .

antl4r:
  stage: test
  before_script:
    - pip install antlr4-tools
  script:
    - antlr4 -o antlr_check -no-listener -no-visitor language/Language.g4
    - rm -r antlr_check/


pymarkdownlnt:
  stage: test
  before_script:
    - pip install pymarkdownlnt
  script:
    - pymarkdown scan docs/

pages:
  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements-mkdocs-build.txt
    - mkdocs --version
    - pwd
  script:
    - mkdocs build
  only:
    - main
  artifacts:
    paths:
    - site
  publish: site
  cache:
    paths:
      - .cache/pip
      - venv

