site_name: SSP Final Project docs
site_author: Martin Minařík, MIN0139

# Copyright
copyright: Copyright &copy; 2023

# Repository
repo_name: SSP Final Project
repo_url: https://gitlab.com/martin-minarik/ssp-final-project


theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.sections
    - navigation.tabs

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.critic:
      mode: view
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Readme: README.md
  - Sample inputs:
      - sample1: sample_input1.md
      - sample2: sample_input2.md
      - sample3: sample_input3.md
  - Language specification: language_specification.md
  - Instruction set: instruction_set.md
  - Coverage report: /ssp-final-project/htmlcov/
