name: Lint Pipeline

on:
  push:
    branches:
      - main
      
jobs:
  lint:
    runs-on: ubuntu-latest

    services:
      antlr:
        image: danistomi/antlr4

    strategy:
      matrix:
        task: [py_compile, black, isort, antlr, pymarkdownlnt]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install black isort pymarkdownlnt

    - name: Lint with Python compile
      if: matrix.task == 'py_compile'
      run: find . -name "*.py" -not -path "./venv/*" -exec python -m py_compile {} +

    - name: Lint with Black
      if: matrix.task == 'black'
      run: black --check .

    - name: Lint with isort
      if: matrix.task == 'isort'
      run: isort --check-only .

    - name: Lint with ANTLR
      if: matrix.task == 'antlr'
      run: |
        antlr4 -o antlr_check -no-listener -no-visitor language/Language.g4
        rm -r antlr_check/

    - name: Lint with pymarkdown
      if: matrix.task == 'pymarkdownlnt'
      run: pymarkdown --disable-rules md013 scan docs/