name: Lint Pipeline

on:
  push:
    branches:
      - main

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          use_pyproject: true

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isort/isort-action@v1
      
  py_compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.12
        
    - run: find . -name "*.py" -not -path "./venv/*" -exec python -m py_compile {} +

  antlr:
    runs-on: ubuntu-latest
    
    container:
      image: danistomi/antlr4
      
    steps:
    - uses: actions/checkout@v3
    - run: |
        antlr4 -o antlr_check -no-listener -no-visitor language/Language.g4
        rm -r antlr_check/

    
